### ISSUE TITLE
问题：this.handleClick = this.handleClick.bind(this);

### ISSUE THREAD

**Issue by imzyf** [ckinmind/gallery-by-react#5]
```
this.handleClick = this.handleClick.bind(this);

onClick={this.handleClick}
```
这是什么意思？

我发现如果不写 `this.handleClick = this.handleClick.bind(this)` 在 `handleClick(e) {}` 方法中会报 `this.props` is null 这是为什么？

**Comment by ckinmind** [comment]
@imzyf 用来绑定this
>1. `React.createClass`创建的组件，其每一个成员函数的this都有React自动绑定，任何时候使用
>2. React.Component创建的组件，其成员函数不会自动绑定this，需要开发者手动绑定，否则this不能获取当前组件实例对象
>3. React.Component有三种手动绑定方法：可以在构造函数中完成绑定，也可以在调用时使用method.bind(this)来完成绑定，还可以使用arrow function来绑定。

更多可以参考这篇博文: [React创建组件的三种方式及其区别](http://www.cnblogs.com/wonyun/p/5930333.html)

**Comment by imzyf** [comment]
非常详细的文章，thx
