### ISSUE TITLE
这里为什么要减 topNum

### ISSUE THREAD

**Issue by imzyf** [ckinmind/gallery-by-react#6]
https://github.com/ckinmind/gallery-by-react/blob/0cef24fba031ba161e977fe2f6667e9413cb785d/src/components/Main.js#L84

**Comment by ckinmind** [comment]
@imzyf 抱歉，因为写的有点早我自己也看不懂这个逻辑了，你可以试试看不减会怎么样

**额外的建议**
>如果是拿这个项目练手react我觉得这不是一个好的项目，太多的计算，对于掌握react的性价比有点低，当然这是以我现在的眼光来看，毕竟这是我第一个react学习的项目

**Comment by imzyf** [comment]
不纠结这个了... 因为是向下取整，删掉也没什么问题
